Repository AllenInstitute/AllenSDK, pull requests merged in 2019-05, with the labels that each got.

#586 Resolve 465 Notebook example for BehaviorOphysSession
  allensdk/brain_observatory/behavior/behavior_ophys_api/behavior_ophys_nwb_api.py
  allensdk/test/brain_observatory/behavior/test_write_nwb_behavior_ophys.py
  doc_template/examples_root/examples/nb/behavior_ophys_session.ipynb
Labels: behavior, task

#612 Resolve GH-441 get_extended_dataframe on behavior ophys api
  allensdk/brain_observatory/behavior/mtrain.py
  allensdk/brain_observatory/behavior/trials_processing.py
  allensdk/internal/api/behavior_ophys_api.py
  allensdk/internal/api/mtrain_api.py
  allensdk/test/brain_observatory/behavior/test_behavior_ophys_lims_api.py
  allensdk/test/brain_observatory/behavior/test_mtrain_annotate.py
Labels: behavior, ophys

#616 Resolve GH-602 cut ophys_timestamps to lenght of dff_traces
  allensdk/__init__.py
  allensdk/brain_observatory/behavior/behavior_ophys_api/behavior_ophys_nwb_api.py
  allensdk/internal/api/behavior_ophys_api.py
Labels: NWB, behavior, ophys

#617 Resolve GH-613 BehaviorOphysLimsApi get_nwb_filepath
  allensdk/internal/api/behavior_ophys_api.py
  allensdk/test/brain_observatory/behavior/test_behavior_ophys_lims_api.py
Labels: NWB, behavior, enhancement

#649 Fast only bamboo
  .travis.yml
  allensdk/test/brain_observatory/behavior/test_behavior_ophys_session.py
  appveyor.yml
  conftest.py
Labels: DevOps

#655 Fix testing framework for AllenSDK .ipynb notebook tests
  Makefile
Labels: DevOps

#651 Upgrade marshmallow dependency to rc6
  .travis.yml
  appveyor.yml
  requirements.txt
Labels: enhancement

#695 Test check write access
  allensdk/brain_observatory/argschema_utilities.py
  allensdk/internal/pipeline_modules/IVSCC/ephys_nwb/nwb_publish.py
  allensdk/internal/pipeline_modules/IVSCC/ephys_nwb/qc.py
  allensdk/test/test_argschema_utilities.py
  requirements.txt
  setup.py
Labels: enhancement

#697 Resolves GH-648 sensible exception when cell_specimen_ids dont exist
  allensdk/brain_observatory/behavior/behavior_ophys_session.py
Labels: enhancement

#619 Resolves GH-618 Fix error message dff_frames longer than timestamps
  allensdk/internal/api/behavior_ophys_api.py
Labels: bug

#698 Resolve GH-627: LazyProperty for average_projection, max_projection, and segmentation_mask_image
  allensdk/brain_observatory/behavior/behavior_ophys_api/__init__.py
  allensdk/brain_observatory/behavior/behavior_ophys_api/behavior_ophys_nwb_api.py
  allensdk/brain_observatory/behavior/behavior_ophys_session.py
  allensdk/brain_observatory/behavior/write_nwb/__main__.py
  allensdk/brain_observatory/behavior/write_nwb/_schemas.py
  allensdk/brain_observatory/nwb/__init__.py
  allensdk/internal/api/behavior_ophys_api.py
  allensdk/internal/api/ophys_lims_api.py
  allensdk/test/brain_observatory/behavior/conftest.py
  allensdk/test/brain_observatory/behavior/test_behavior_lims_api.py
  allensdk/test/brain_observatory/behavior/test_behavior_ophys_session.py
  allensdk/test/brain_observatory/behavior/test_mtrain_annotate.py
  allensdk/test/brain_observatory/behavior/test_ophys_lims_api.py
  allensdk/test/brain_observatory/behavior/test_write_nwb_behavior_ophys.py
  doc_template/examples_root/examples/nb/behavior_ophys_session.ipynb
Labels: NWB, behavior, bug, enhancement, ophys
