Repository AllenInstitute/AllenSDK, pull requests merged in 2020-04, with the labels that each got.

#1490 Simplify API classes for ecephys NWB extension
  allensdk/brain_observatory/ecephys/nwb/__init__.py
Labels: braintv

#1498 Change ecephys optotagging table "name" column to "stimulus_name"
  allensdk/brain_observatory/ecephys/optotagging_table/__main__.py
  allensdk/brain_observatory/ecephys/write_nwb/__main__.py
  allensdk/test/brain_observatory/ecephys/test_write_nwb.py
Labels: braintv

#1503 Fix errors when trying to run ecephys write_nwb with LIMS
  allensdk/brain_observatory/ecephys/ecephys_session_api/ecephys_nwb_session_api.py
  allensdk/brain_observatory/ecephys/write_nwb/__main__.py
  allensdk/brain_observatory/ecephys/write_nwb/_schemas.py
  allensdk/test/brain_observatory/ecephys/test_write_nwb.py
Labels: braintv

#1474 fix for off-by-one error in encoder data
  allensdk/brain_observatory/behavior/running_processing.py
Labels: braintv

#1451 rc/1.7.0
  CHANGELOG.md
  CODEOWNERS
  allensdk/__init__.py
  allensdk/brain_observatory/behavior/behavior_ophys_api/__init__.py
  allensdk/brain_observatory/behavior/behavior_ophys_session.py
  allensdk/brain_observatory/behavior/behavior_project_lims_api.py
  allensdk/brain_observatory/behavior/eye_tracking_processing.py
  allensdk/brain_observatory/session_api_utils.py
  allensdk/brain_observatory/sync_dataset.py
  allensdk/internal/api/behavior_ophys_api.py
  allensdk/internal/api/ophys_lims_api.py
  allensdk/internal/api/queries/pre_release_sql/cell_specimens_pre_release_query.sql
  allensdk/internal/api/queries/pre_release_sql/experiment_pre_release_query.sql
  allensdk/internal/brain_observatory/time_sync.py
  allensdk/test/brain_observatory/behavior/test_behavior_data_lims_api.py
  allensdk/test/brain_observatory/behavior/test_behavior_ophys_session.py
  allensdk/test/brain_observatory/behavior/test_eye_tracking_processing.py
  allensdk/test/brain_observatory/test_session_api_utils.py
  allensdk/test/internal/brain_observatory/test_time_sync.py
  doc_template/examples_root/examples/internal/Using updated behavior project cache to access eye tracking data.ipynb
  doc_template/index.rst
Labels: noprogram

#1522 Update AIBS_ecephys_namespace.yaml
  allensdk/brain_observatory/ecephys/nwb/AIBS_ecephys_namespace.yaml
  allensdk/brain_observatory/nwb/AIBS_ophys_behavior_namespace.yaml
Labels: NWB

#1500 GH 1487: Deprecate duplicated internal demixer and add tests
  allensdk/brain_observatory/demixer.py
  allensdk/internal/brain_observatory/demixer.py
  allensdk/internal/pipeline_modules/run_demixing.py
  allensdk/test/brain_observatory/test_demixer.py
Labels: braintv

#1512 Update contribution guidelines
  CONTRIBUTING.md
Labels: noprogram
