Repository AllenInstitute/AllenSDK, pull requests merged in 2020-05, with the labels that each got.

#1534 GH 1524: Updating Allen SDK install guide
  doc_template/install.rst
Labels: documentation, noprogram

#1562 1076 remove ecephys warehouse structure assignment patch
  allensdk/brain_observatory/ecephys/ecephys_project_api/ecephys_project_warehouse_api.py
  allensdk/brain_observatory/ecephys/ecephys_project_api/warehouse_patches/__init__.py
  allensdk/brain_observatory/ecephys/ecephys_project_api/warehouse_patches/data/732592105_probeB_733744647.csv
  allensdk/brain_observatory/ecephys/ecephys_project_api/warehouse_patches/data/732592105_probeC_733744649.csv
  allensdk/brain_observatory/ecephys/ecephys_project_api/warehouse_patches/data/732592105_probeD_733744651.csv
  allensdk/brain_observatory/ecephys/ecephys_project_api/warehouse_patches/data/732592105_probeE_733744653.csv
  allensdk/brain_observatory/ecephys/ecephys_project_api/warehouse_patches/data/732592105_probeF_733744655.csv
  allensdk/brain_observatory/ecephys/ecephys_project_api/warehouse_patches/data/799864342_probeA_805579698.csv
  allensdk/brain_observatory/ecephys/ecephys_project_api/warehouse_patches/data/829720705_probeA_832129149.csv
  allensdk/brain_observatory/ecephys/ecephys_project_api/warehouse_patches/data/835479236_probeC_837761710.csv
Labels: braintv

#1553 Updating Python and AllenSDK versions on the AllenSDK docker image
  doc_template/install.rst
  docker/allensdk/Dockerfile
Labels: DevOps, noprogram

#1570 1482 add ecephys ccf coords
  allensdk/brain_observatory/ecephys/write_nwb/__main__.py
  allensdk/brain_observatory/ecephys/write_nwb/_schemas.py
  allensdk/test/brain_observatory/ecephys/test_write_nwb.py
Labels: NWB, neuropixels

#1588 Gh 1363: Add acquisition date to behavior session summary table
  allensdk/brain_observatory/behavior/behavior_project_cache.py
  allensdk/brain_observatory/behavior/behavior_project_lims_api.py
  doc_template/examples_root/examples/internal/Lims Behavior Project Cache.ipynb
Labels: braintv, internal

#1589 Bugfix: Asynchronous Http Engine initialization in EcephysProjectCache
  allensdk/brain_observatory/ecephys/ecephys_project_api/ecephys_project_lims_api.py
  allensdk/brain_observatory/ecephys/ecephys_project_api/ecephys_project_warehouse_api.py
  allensdk/brain_observatory/ecephys/ecephys_project_api/http_engine.py
  allensdk/brain_observatory/ecephys/ecephys_project_cache.py
  allensdk/test/brain_observatory/ecephys/test_ecephys_project_cache.py
Labels: braintv

#1579 Added pull request template to root directory of repo
  pull_request_template.md
Labels: noprogram
