Repository AllenInstitute/AllenSDK, pull requests merged in 2020-03, with the labels that each got.

#1397 GH 771: Remove redundant 'sham_change' column from trials
  allensdk/brain_observatory/behavior/trials_processing.py
Labels: braintv

#1413 Do checksums for data files in chunks
  allensdk/brain_observatory/ecephys/copy_utility/__main__.py
Labels: braintv

#1244 Add alias for _get_rf
  allensdk/brain_observatory/ecephys/stimulus_analysis/receptive_field_mapping.py
Labels: braintv, neuropixels

#1359 add version to AIBS_ophys_behavior
  allensdk/brain_observatory/nwb/AIBS_ophys_behavior_namespace.yaml
Labels: NWB, braintv, external, ophys

#1373 GH 1357: Project caches should not accept arbitrary kwargs
  allensdk/brain_observatory/behavior/behavior_project_cache.py
  allensdk/brain_observatory/ecephys/ecephys_project_cache.py
  allensdk/test/brain_observatory/ecephys/test_ecephys_project_cache.py
  doc_template/examples_root/examples/internal/Lims Behavior Project Cache.ipynb
Labels: braintv

#1453 ophys_sessions table does not always have imaging_depth_id
  CHANGELOG.md
  allensdk/internal/api/behavior_ophys_api.py
  allensdk/internal/api/ophys_lims_api.py
  allensdk/internal/api/queries/pre_release_sql/cell_specimens_pre_release_query.sql
  allensdk/internal/api/queries/pre_release_sql/experiment_pre_release_query.sql
Labels: braintv

#1456 remove redundant sham_change column from test
  allensdk/test/brain_observatory/behavior/test_behavior_data_lims_api.py
Labels: braintv

#1417 1394 add eye tracking to behavior ophys session
  CHANGELOG.md
  allensdk/brain_observatory/behavior/behavior_ophys_api/__init__.py
  allensdk/brain_observatory/behavior/behavior_ophys_session.py
  allensdk/brain_observatory/behavior/eye_tracking_processing.py
  allensdk/brain_observatory/session_api_utils.py
  allensdk/internal/api/behavior_ophys_api.py
  allensdk/test/brain_observatory/behavior/test_behavior_ophys_session.py
  allensdk/test/brain_observatory/behavior/test_eye_tracking_processing.py
  allensdk/test/brain_observatory/test_session_api_utils.py
  doc_template/examples_root/examples/internal/Using updated behavior project cache to access eye tracking data.ipynb
  doc_template/index.rst
Labels: braintv

#1438 GH-1404: Handle monitor delay errors
  CHANGELOG.md
  allensdk/internal/brain_observatory/time_sync.py
  allensdk/test/internal/brain_observatory/test_time_sync.py
  doc_template/index.rst
Labels: braintv

#1470 Add additional possible sync file line label keys
  CHANGELOG.md
  allensdk/brain_observatory/sync_dataset.py
  doc_template/index.rst
Labels: braintv
