Repository AllenInstitute/AllenSDK, pull requests merged in 2020-09, with the labels that each got.

#1665 rc/2.2.0
  CHANGELOG.md
  allensdk/__init__.py
  allensdk/brain_observatory/behavior/behavior_ophys_session.py
  allensdk/brain_observatory/behavior/trials_processing.py
  allensdk/brain_observatory/behavior/write_nwb/__main__.py
  allensdk/brain_observatory/behavior/write_nwb/_schemas.py
  allensdk/brain_observatory/demixer.py
  allensdk/brain_observatory/ecephys/ecephys_project_api/http_engine.py
  allensdk/brain_observatory/ecephys/ecephys_session_api/ecephys_nwb_session_api.py
  allensdk/internal/api/ophys_lims_api.py
  allensdk/test/brain_observatory/behavior/test_behavior_ophys_session.py
  allensdk/test/brain_observatory/behavior/test_ophys_lims_api.py
  allensdk/test/brain_observatory/behavior/test_trials_processing.py
  allensdk/test/brain_observatory/ecephys/test_write_nwb.py
  allensdk/test/brain_observatory/test_demixer.py
  doc_template/index.rst
  docker/anaconda3/Dockerfile
  docker/anaconda3/shared/apt_get_dependencies.sh
  docker/anaconda3/shared/conda_27.sh
  docker/anaconda3/shared/conda_36.sh
  requirements.txt
  test_requirements.txt
Labels: noprogram

#1678 Add gratings to stimulus metadata and removes 'image' key breaking dependencies in stimulus_processing.py
  allensdk/brain_observatory/behavior/stimulus_processing.py
  allensdk/brain_observatory/behavior/trials_processing.py
  allensdk/internal/api/behavior_data_lims_api.py
  allensdk/test/brain_observatory/behavior/conftest.py
  allensdk/test/brain_observatory/behavior/test_stimulus_processing.py
  allensdk/test/brain_observatory/behavior/test_trials_processing.py
Labels: behavior

#1697 GH #1671: Filtered+corrected running speed
  allensdk/brain_observatory/behavior/behavior_data_session.py
  allensdk/brain_observatory/behavior/behavior_ophys_session.py
  allensdk/brain_observatory/behavior/running_processing.py
  allensdk/internal/api/behavior_data_lims_api.py
  allensdk/internal/api/behavior_ophys_api.py
  allensdk/test/brain_observatory/behavior/test_behavior_data_lims_api.py
  allensdk/test/brain_observatory/behavior/test_running_processing.py
  allensdk/test/brain_observatory/extract_running_speed/test_extract_running_speed_module.py
Labels: braintv

#1713 GH-1682/feature/eye tracking mismatch
  allensdk/brain_observatory/sync_utilities/__init__.py
  allensdk/internal/api/behavior_ophys_api.py
  allensdk/test/brain_observatory/sync_utilities/test_sync_utilities.py
Labels: braintv
