Repository AllenInstitute/AllenSDK, pull requests merged in 2021-02, with the labels that each got.

#1835 Updates lick events to use Events data type
  allensdk/brain_observatory/behavior/session_apis/abcs/behavior_base.py
  allensdk/brain_observatory/behavior/session_apis/data_io/behavior_ophys_nwb_api.py
  allensdk/brain_observatory/nwb/__init__.py
  requirements.txt
Labels: braintv

#1825 1356 behavior nwb
  CHANGELOG.md
  allensdk/brain_observatory/behavior/behavior_session.py
  allensdk/brain_observatory/behavior/metadata_processing.py
  allensdk/brain_observatory/behavior/project_apis/data_io/behavior_project_lims_api.py
  allensdk/brain_observatory/behavior/schemas.py
  allensdk/brain_observatory/behavior/session_apis/data_io/__init__.py
  allensdk/brain_observatory/behavior/session_apis/data_io/behavior_json_api.py
  allensdk/brain_observatory/behavior/session_apis/data_io/behavior_lims_api.py
  allensdk/brain_observatory/behavior/session_apis/data_io/behavior_nwb_api.py
  allensdk/brain_observatory/behavior/session_apis/data_io/behavior_ophys_json_api.py
  allensdk/brain_observatory/behavior/session_apis/data_io/behavior_ophys_nwb_api.py
  allensdk/brain_observatory/behavior/session_apis/data_transforms/behavior_data_xforms.py
  allensdk/brain_observatory/behavior/session_apis/data_transforms/behavior_ophys_data_xforms.py
  allensdk/brain_observatory/behavior/write_behavior_nwb/__init__.py
  allensdk/brain_observatory/behavior/write_behavior_nwb/__main__.py
  allensdk/brain_observatory/behavior/write_behavior_nwb/_schemas.py
  allensdk/brain_observatory/nwb/__init__.py
  allensdk/brain_observatory/nwb/behavior_ophys_nwb_extension_builder.py
  allensdk/brain_observatory/nwb/metadata.py
  allensdk/brain_observatory/nwb/ndx-aibs-behavior-ophys.extension.yaml
  allensdk/test/brain_observatory/behavior/conftest.py
  allensdk/test/brain_observatory/behavior/test_write_behavior_nwb.py
  allensdk/test/brain_observatory/behavior/test_write_nwb_behavior_ophys.py
  doc_template/index.rst
Labels: braintv

#1834 Adds eye tracking data to NWB
  CHANGELOG.md
  allensdk/brain_observatory/behavior/behavior_ophys_session.py
  allensdk/brain_observatory/behavior/schemas.py
  allensdk/brain_observatory/behavior/session_apis/abcs/behavior_ophys_base.py
  allensdk/brain_observatory/behavior/session_apis/data_io/behavior_ophys_json_api.py
  allensdk/brain_observatory/behavior/session_apis/data_io/behavior_ophys_nwb_api.py
  allensdk/brain_observatory/behavior/write_nwb/_schemas.py
  allensdk/brain_observatory/nwb/__init__.py
  allensdk/brain_observatory/nwb/behavior_ophys_nwb_extension_builder.py
  allensdk/brain_observatory/nwb/eye_tracking/__init__.py
  allensdk/brain_observatory/nwb/eye_tracking/extension_builder.py
  allensdk/brain_observatory/nwb/eye_tracking/ndx-ellipse-eye-tracking.extensions.yaml
  allensdk/brain_observatory/nwb/eye_tracking/ndx-ellipse-eye-tracking.namespace.yaml
  allensdk/brain_observatory/nwb/eye_tracking/ndx_ellipse_eye_tracking.py
  allensdk/brain_observatory/nwb/metadata.py
  allensdk/brain_observatory/nwb/ndx-aibs-behavior-ophys.extension.yaml
  allensdk/test/brain_observatory/behavior/test_write_nwb_behavior_ophys.py
  doc_template/index.rst
Labels: braintv

#1831 Bug1828/dev/dff/roi/association
  CHANGELOG.md
  allensdk/brain_observatory/behavior/session_apis/data_transforms/behavior_ophys_data_xforms.py
  allensdk/test/brain_observatory/behavior/test_behavior_ophys_lims_api.py
  doc_template/index.rst
Labels: braintv

#1839 rc/2.5.1
  CHANGELOG.md
  allensdk/__init__.py
  allensdk/brain_observatory/behavior/session_apis/data_transforms/behavior_ophys_data_xforms.py
  allensdk/test/brain_observatory/behavior/test_behavior_ophys_lims_api.py
  allensdk/test/brain_observatory/behavior/test_behavior_ophys_session.py
  doc_template/index.rst
Labels: noprogram

#1850 Fix eye tracking bug after resolving merge conflicts and adds LIMS interface
  allensdk/brain_observatory/behavior/session_apis/abcs/behavior_ophys_base.py
  allensdk/brain_observatory/behavior/session_apis/data_io/behavior_ophys_lims_api.py
  allensdk/brain_observatory/behavior/session_apis/data_io/behavior_ophys_nwb_api.py
  allensdk/test/brain_observatory/behavior/resources/rig_geometry_multiple_rig_configs.pkl
  allensdk/test/brain_observatory/behavior/test_behavior_ophys_lims_api.py
  allensdk/test/brain_observatory/behavior/test_write_nwb_behavior_ophys.py
Labels: braintv

#1856 1841 resolve circular inheritance
  CHANGELOG.md
  allensdk/brain_observatory/behavior/behavior_ophys_session.py
  allensdk/brain_observatory/behavior/session_apis/abcs/__init__.py
  allensdk/brain_observatory/behavior/session_apis/abcs/behavior_data_extractor_base.py
  allensdk/brain_observatory/behavior/session_apis/abcs/behavior_ophys_base.py
  allensdk/brain_observatory/behavior/session_apis/abcs/behavior_ophys_data_extractor_base.py
  allensdk/brain_observatory/behavior/session_apis/data_io/__init__.py
  allensdk/brain_observatory/behavior/session_apis/data_io/behavior_json_api.py
  allensdk/brain_observatory/behavior/session_apis/data_io/behavior_lims_api.py
  allensdk/brain_observatory/behavior/session_apis/data_io/behavior_ophys_json_api.py
  allensdk/brain_observatory/behavior/session_apis/data_io/behavior_ophys_lims_api.py
  allensdk/brain_observatory/behavior/session_apis/data_io/behavior_ophys_nwb_api.py
  allensdk/brain_observatory/behavior/session_apis/data_io/ophys_lims_api.py
  allensdk/brain_observatory/behavior/session_apis/data_transforms/__init__.py
  allensdk/brain_observatory/behavior/session_apis/data_transforms/behavior_data_transforms.py
  allensdk/brain_observatory/behavior/session_apis/data_transforms/behavior_ophys_data_transforms.py
  allensdk/test/brain_observatory/behavior/conftest.py
  allensdk/test/brain_observatory/behavior/test_behavior_data_lims_api.py
  allensdk/test/brain_observatory/behavior/test_behavior_lims_api.py
  allensdk/test/brain_observatory/behavior/test_behavior_ophys_data_xforms.py
  allensdk/test/brain_observatory/behavior/test_behavior_ophys_lims_api.py
  allensdk/test/brain_observatory/behavior/test_behavior_ophys_session.py
  allensdk/test/brain_observatory/behavior/test_behavior_session.py
  allensdk/test/brain_observatory/behavior/test_ophys_lims_api.py
  allensdk/test/brain_observatory/behavior/test_trials_processing.py
  doc_template/index.rst
Labels: braintv

#1867 1866-modifies access to roi_masks
  CHANGELOG.md
  allensdk/brain_observatory/behavior/behavior_ophys_session.py
  allensdk/test/brain_observatory/behavior/test_behavior_ophys_session.py
  doc_template/index.rst
Labels: braintv

#1864 modify eye_tracking_processing.py to remove CR from outlier detection
  allensdk/brain_observatory/behavior/eye_tracking_processing.py
Labels: braintv

#1868 1784 running speed dataframe
  allensdk/brain_observatory/behavior/behavior_ophys_session.py
  allensdk/brain_observatory/behavior/behavior_session.py
  allensdk/brain_observatory/behavior/session_apis/abcs/behavior_base.py
  allensdk/brain_observatory/behavior/session_apis/data_io/behavior_nwb_api.py
  allensdk/brain_observatory/behavior/session_apis/data_io/behavior_ophys_nwb_api.py
  allensdk/brain_observatory/behavior/swdb/behavior_project_cache.py
  allensdk/test/brain_observatory/behavior/test_write_behavior_nwb.py
  allensdk/test/brain_observatory/behavior/test_write_nwb_behavior_ophys.py
Labels: braintv

#1877 removes df write to nwb for running speed
  allensdk/brain_observatory/behavior/session_apis/data_io/behavior_nwb_api.py
  allensdk/brain_observatory/behavior/session_apis/data_io/behavior_ophys_nwb_api.py
  allensdk/brain_observatory/nwb/__init__.py
  allensdk/test/brain_observatory/behavior/test_write_behavior_nwb.py
  allensdk/test/brain_observatory/behavior/test_write_nwb_behavior_ophys.py
Labels: braintv

#1891 adds case for sessions with no omitted flash frames
  allensdk/brain_observatory/behavior/stimulus_processing.py
Labels: braintv

#1881 adds flake8 linting job to circleci
  .circleci/config.yml
Labels: braintv

#1890 issue 1862 convert pupil_area to NaN where likely_blink == True (draft)
  allensdk/brain_observatory/behavior/behavior_ophys_session.py
  allensdk/brain_observatory/behavior/eye_tracking_processing.py
  allensdk/brain_observatory/behavior/session_apis/data_io/behavior_ophys_nwb_api.py
  allensdk/test/brain_observatory/behavior/test_eye_tracking_processing.py
  allensdk/test/brain_observatory/behavior/test_write_nwb_behavior_ophys.py
Labels: braintv

#1912 stimulus_templates in Session API returns object keyed by image name
  CHANGELOG.md
  allensdk/brain_observatory/behavior/behavior_ophys_session.py
  allensdk/brain_observatory/behavior/session_apis/abcs/behavior_base.py
  allensdk/brain_observatory/behavior/session_apis/data_io/behavior_nwb_api.py
  allensdk/brain_observatory/behavior/session_apis/data_io/behavior_ophys_nwb_api.py
  allensdk/brain_observatory/behavior/session_apis/data_transforms/behavior_data_transforms.py
  allensdk/brain_observatory/behavior/stimulus_processing/__init__.py
  allensdk/brain_observatory/behavior/stimulus_processing/stimulus_templates.py
  allensdk/brain_observatory/behavior/stimulus_processing/util.py
  allensdk/brain_observatory/nwb/__init__.py
  allensdk/test/brain_observatory/behavior/conftest.py
  allensdk/test/brain_observatory/behavior/resources/test_image_set.pkl
  allensdk/test/brain_observatory/behavior/test_behavior_ophys_session.py
  allensdk/test/brain_observatory/behavior/test_stimulus_processing.py
  allensdk/test/brain_observatory/behavior/test_write_behavior_nwb.py
  allensdk/test/brain_observatory/behavior/test_write_nwb_behavior_ophys.py
Labels: braintv

#1905 1884 mesoscope nwb
  CHANGELOG.md
  allensdk/brain_observatory/behavior/behavior_ophys_session.py
  allensdk/brain_observatory/behavior/behavior_session.py
  allensdk/brain_observatory/behavior/eye_tracking_processing.py
  allensdk/brain_observatory/behavior/schemas.py
  allensdk/brain_observatory/behavior/session_apis/abcs/behavior_base.py
  allensdk/brain_observatory/behavior/session_apis/abcs/behavior_data_extractor_base.py
  allensdk/brain_observatory/behavior/session_apis/abcs/behavior_ophys_data_extractor_base.py
  allensdk/brain_observatory/behavior/session_apis/data_io/behavior_json_api.py
  allensdk/brain_observatory/behavior/session_apis/data_io/behavior_lims_api.py
  allensdk/brain_observatory/behavior/session_apis/data_io/behavior_nwb_api.py
  allensdk/brain_observatory/behavior/session_apis/data_io/behavior_ophys_json_api.py
  allensdk/brain_observatory/behavior/session_apis/data_io/behavior_ophys_lims_api.py
  allensdk/brain_observatory/behavior/session_apis/data_io/behavior_ophys_nwb_api.py
  allensdk/brain_observatory/behavior/session_apis/data_transforms/behavior_data_transforms.py
  allensdk/brain_observatory/behavior/session_apis/data_transforms/behavior_ophys_data_transforms.py
  allensdk/brain_observatory/behavior/stimulus_processing/stimulus_templates.py
  allensdk/brain_observatory/behavior/swdb/behavior_project_cache.py
  allensdk/brain_observatory/behavior/swdb/summary_figures.py
  allensdk/brain_observatory/behavior/write_behavior_nwb/__main__.py
  allensdk/brain_observatory/behavior/write_nwb/__main__.py
  allensdk/brain_observatory/behavior/write_nwb/_schemas.py
  allensdk/brain_observatory/behavior/write_nwb/extensions/event_detection/extension_builder.py
  allensdk/brain_observatory/behavior/write_nwb/extensions/event_detection/ndx-aibs-ophys-event-detection.extensions.yaml
  allensdk/brain_observatory/behavior/write_nwb/extensions/event_detection/ndx-aibs-ophys-event-detection.namespace.yaml
  allensdk/brain_observatory/behavior/write_nwb/extensions/event_detection/ndx-event-detection.namespace.yaml
  allensdk/brain_observatory/behavior/write_nwb/extensions/event_detection/ndx_events.py
  allensdk/brain_observatory/behavior/write_nwb/extensions/event_detection/ndx_ophys_events.py
  allensdk/brain_observatory/ecephys/ecephys_session_api/ecephys_nwb1_session_api.py
  allensdk/brain_observatory/nwb/__init__.py
  allensdk/brain_observatory/nwb/behavior_ophys_nwb_extension_builder.py
  allensdk/brain_observatory/nwb/ndx-aibs-behavior-ophys.extension.yaml
  allensdk/brain_observatory/session_api_utils.py
  allensdk/core/lazy_property/lazy_property.py
  allensdk/test/brain_observatory/behavior/conftest.py
  allensdk/test/brain_observatory/behavior/test_behavior_data_transforms.py
  allensdk/test/brain_observatory/behavior/test_behavior_lims_api.py
  allensdk/test/brain_observatory/behavior/test_behavior_ophys_session.py
  allensdk/test/brain_observatory/behavior/test_behavior_session.py
  allensdk/test/brain_observatory/behavior/test_write_behavior_nwb.py
  allensdk/test/brain_observatory/behavior/test_write_nwb_behavior_ophys.py
  doc_template/index.rst
Labels: behavior

#1937 Ticket/1932/dev
  CHANGELOG.md
  allensdk/brain_observatory/behavior/eye_tracking_processing.py
  allensdk/test/brain_observatory/behavior/test_eye_tracking_processing.py
  doc_template/index.rst
Labels: braintv

#1943 Improvements to stimulus_template in NWB
  allensdk/brain_observatory/behavior/write_nwb/extensions/stimulus_template/extension_builder.py
  allensdk/brain_observatory/nwb/__init__.py
Labels: braintv

#1941 1667 add gratings to stimulus templates
  allensdk/brain_observatory/behavior/behavior_session.py
  allensdk/brain_observatory/behavior/session_apis/data_io/behavior_nwb_api.py
  allensdk/brain_observatory/behavior/session_apis/data_io/behavior_ophys_nwb_api.py
  allensdk/brain_observatory/behavior/session_apis/data_transforms/behavior_data_transforms.py
  allensdk/brain_observatory/behavior/stimulus_processing/__init__.py
  allensdk/brain_observatory/behavior/stimulus_processing/stimulus_templates.py
  allensdk/test/brain_observatory/behavior/conftest.py
  allensdk/test/brain_observatory/behavior/test_behavior_lims_api.py
  allensdk/test/brain_observatory/behavior/test_behavior_ophys_session.py
  allensdk/test/brain_observatory/behavior/test_stimulus_processing.py
  allensdk/test/brain_observatory/behavior/test_write_behavior_nwb.py
  allensdk/test/internal/brain_observatory/test_time_sync.py
Labels: braintv
